const genres = {
  Action: [
    'Disaster film',
    'Heroic bloodshed',
    'Martial arts film',
    'Spy film',
    'Super Hero',
    'War film',
    'Action Comedy',
    'Action Thriller',
    'Action Horror',
    'Action Adventure',
    'Arthouse Action',
    'Vigilante film'
  ],
  Adventure: [
    'Pirate film',
    'Swashbuckler film',
    'Samurai film',
    'Treasure Hunt',
    'Survival',
    'Sea Adventure',
    'Space Exploration'
  ],
  Comedy: [
    'Action comedy film',
    'Buddy comedy',
    'Dark/black comedy film',
    'Mockumentary',
    'Parody film',
    'Romantic comedy',
    'Screwball comedy',
    'Slapstick film',
    'Satire',
    'Situational Comedy',
    'Comedy Thriller',
    'Anarchic comedy',
    'Bathroom comedy',
    'Comedy of ideas',
    'Comedy of manners',
    'Observational humor',
    'Sex comedy',
    'Straight comedy',
    'Surreal comedy',
    'Comedy horror',
    'Fantasy comedy',
    'Crime Comedy',
    'Day-in-the-life comedy',
    'Science fiction comedy',
    'Sports comedy',
    'War comedy',
    'Comedy mystery'
  ],
  Drama: [
    'Docudrama',
    'Legal drama',
    'Medical drama',
    'Melodrama',
    'Political drama',
    'Psychological drama',
    'Teen drama',
    'Comedy drama',
    'Hyperdrama',
    'Light drama',
    'Psychological drama',
    'Satirical drama',
    'Straight drama',
    'Crime Drama',
    'Action drama',
    'Drama thriller',
    'Fantasy drama',
    'Horror drama',
    'Life drama',
    'Romantic drama',
    'Science fiction drama',
    'Sports drama',
    'War drama',
    'Western drama',
    'Family drama',
    'Religious drama',
    'Police procedural',
    'Historical drama'
  ],
  Fantasy: [
    'Contemporary fantasy',
    'Dark fantasy',
    'High/epic fantasy',
    'Urban fantasy',
    'Heroic fantasy',
    'Mythological Fantasy',
    'Fairy Tale'
  ],
  Historical: [
    'Alternate history',
    'Biopic',
    'Historical epic',
    'Historical event',
    'Historical fiction',
    'Period piece'
  ],
  Horror: [
    'Found footage',
    'Ghost films',
    'Monster movie',
    'Vampire films',
    'Werewolf films',
    'Slasher film',
    'Splatter film',
    'Zombie film',
    'Supernatural horror',
    'Body horror',
    'Erotic horror',
    'Folk horror',
    'Gothic horror',
    'Natural horror',
    'Religious horror',
    'Psychological horror',
    'Teen horror'
  ],
  Musical: [
    'Traditional Musical',
    'Musical Comedy',
    'Musical Drama',
    'Animated Musical',
    'Rock Musical',
    'Jukebox Musical',
    'Fantasy Musical',
    'Biographical Musical'
  ],
  Romance: [
    'Historical romance',
    'Paranormal romance',
    'Romantic comedy',
    'Romantic fantasy',
    'Romantic thriller',
    'Romantic Drama',
    'Chick Flick'
  ],
  'Science Fiction': [
    'Dystopian film',
    'Post-apocalyptic film',
    'Military science fiction',
    'Steampunk film',
    'Tech noir',
    'Utopian film',
    'Space opera',
    'Hard Science Fiction',
    'Soft Science Fiction',
    'Cyberpunk',
    'Time Travel',
    'Alien Film',
    'Superhero',
    'Steampunk'
  ],
  Thriller: [
    'Psychological thriller',
    'Mystery film',
    'Techno-thriller',
    'Political thriller',
    'Crime Thriller',
    'Spy Thriller',
    'Legal Thriller',
    'Action Thriller',
    'Horror Thriller',
    'Erotic Thriller'
  ]
}
const prefixEnum: string[] = ['Screenplay by', 'Written by']
const editStatusEnum: string[] = [
  'PERSONAL DRAFT',
  'DRAFT',
  'IN PROGRESS',
  'FINAL'
]
const versionColorEnum: string[] = [
  'White',
  'Blue',
  'Pink',
  'Yellow',
  'Green',
  'Goldenrod',
  'Buff',
  'Salmon',
  'Cherry',
  'Tan',
  'Lavender',
  '2nd white',
  '2nd Blue',
  '2nd Pink',
  '2nd Yellow',
  '2nd Green',
  '2nd Goldenrod',
  '2nd Buff',
  '2nd Salmon',
  '2nd Cherry',
  '2nd Tan',
  '2nd Lavender'
]
const typeOfCreationEnum: string[] = [
  'Feature Film',
  'Web Series',
  'Tv Show',
  'Short Film'
]
export {
  genres,
  prefixEnum,
  typeOfCreationEnum,
  editStatusEnum,
  versionColorEnum
}
