export const shots = [
    {
        _id: "1",
        stared: false,
        shotName: "1B",
        duration: 5,
        requiredTime: 2,
        estimatedTime: 2,
        filmed: false,
        image: "https://thumbs.dreamstime.com/b/template-sketch-trend-artwork-d-photo-collage-film-tape-strip-shooting-moment-photo-author-cadre-young-woman-stand-hold-camera-360665992.jpg",
        tags: ["Shallow Depth Of Field", "Crane", "Forward", "Wide Shot", "Overhead", "Point of View", "180mm", "Static"],
        description: "Shot description and long description",
        shotSize: 10,
        movement: "Move",
        shotType: "Type"
    },
    {
        _id: "2",
        stared: false,
        shotName: "2B",
        duration: 5,
        requiredTime: 2,
        estimatedTime: 2,
        filmed: true,
        image: "https://thumbs.dreamstime.com/b/template-sketch-trend-artwork-d-photo-collage-film-tape-strip-shooting-moment-photo-author-cadre-young-woman-stand-hold-camera-360665992.jpg",
        tags: ["Shallow Depth Of Field", "Crane", "Forward", "Wide Shot", "Overhead", "Point of View", "180mm", "Static"],
        description: "Shot description 2",
        shotSize: 10,
        movement: "Move",
        shotType: "Type"
    },
    {
        _id: "3",
        stared: false,
        shotName: "3B",
        duration: 5,
        requiredTime: 2,
        estimatedTime: 2,
        filmed: false,
        image: "https://thumbs.dreamstime.com/b/template-sketch-trend-artwork-d-photo-collage-film-tape-strip-shooting-moment-photo-author-cadre-young-woman-stand-hold-camera-360665992.jpg",
        tags: ["Shallow Depth Of Field", "Crane", "Forward", "Wide Shot", "Overhead", "Point of View", "180mm", "Static"],
        description: "Shot description 3",
        shotSize: 10,
        movement: "Move",
        shotType: "Type"
    },
    {
        _id: "4",
        stared: false,
        shotName: "4B",
        duration: 5,
        requiredTime: 2,
        estimatedTime: 2,
        filmed: false,
        image: "https://thumbs.dreamstime.com/b/template-sketch-trend-artwork-d-photo-collage-film-tape-strip-shooting-moment-photo-author-cadre-young-woman-stand-hold-camera-360665992.jpg",
        tags: ["Shallow Depth Of Field", "Crane", "Forward", "Wide Shot", "Overhead", "Point of View", "180mm", "Static"],
        description: "Shot description 4",
        shotSize: 10,
        movement: "Move",
        shotType: "Type"
    },
    {
        _id: "5",
        stared: false,
        shotName: "5B",
        duration: 5,
        requiredTime: 2,
        estimatedTime: 2,
        filmed: false,
        image: "https://thumbs.dreamstime.com/b/template-sketch-trend-artwork-d-photo-collage-film-tape-strip-shooting-moment-photo-author-cadre-young-woman-stand-hold-camera-360665992.jpg",
        tags: ["Shallow Depth Of Field", "Crane", "Forward", "Wide Shot", "Overhead", "Point of View", "180mm", "Static"],
        description: "Shot description 5",
        shotSize: 10,
        movement: "Move",
        shotType: "Type"
    },
    {
        _id: "6",
        stared: false,
        shotName: "6B",
        duration: 5,
        requiredTime: 2,
        estimatedTime: 2,
        filmed: false,
        image: "https://thumbs.dreamstime.com/b/template-sketch-trend-artwork-d-photo-collage-film-tape-strip-shooting-moment-photo-author-cadre-young-woman-stand-hold-camera-360665992.jpg",
        tags: ["Shallow Depth Of Field", "Crane", "Forward", "Wide Shot", "Overhead", "Point of View", "180mm", "Static"],
        description: "Shot description 6",
        shotSize: 10,
        movement: "Move",
        shotType: "Type"
    },
]